  import Head from "next/head";
  import Helmet from "@/components/Helmet";
  import Style from "@/styles/Home.module.scss";
  import HomeContent from "@/components/HomeContent";
  import Game from "@/components/Snake/Game";
  import Container from "@/components/Container"

  export default function Home() {
    return (
        <Container>
          <Helmet title="Home" />
          <Head>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.png" />
          </Head>
          <div className={Style.Home}>
            <HomeContent />
            <div className={Style.Game}>
              <Game />
            </div>
          </div>
        </Container>
    );
  }
